In [54]:
import numpy as np
import random 

In [108]:
UP = "00"
DOWN = "01"
LEFT = "10"
RIGHT = "11"
ACTIONS = [UP, DOWN, LEFT, RIGHT]
# Define a matrix
gridSize = [3,3]
matrix = np.empty((3, 3),dtype=object)
def genmatrix(shape):
    for i in range(0,shape[0]):
        for j in range(0,shape[1]):
            matrix[i][j] = ACTIONS[random.randint(0,3)]
    return matrix
matrix = genmatrix(gridSize)
print(matrix)

[['01' '10' '01']
 ['00' '11' '01']
 ['00' '10' '10']]


In [104]:
target = genmatrix(gridSize)
print(target)

[['00' '01' '10']
 ['01' '10' '11']
 ['11' '11' '10']]


In [109]:
def circuits_check(matrix,target):
    if matrix.shape != target.shape: 
        raise ValueError(f"Different shapes error")
    else:
        result = np.empty((3, 3),dtype=int)
        for i in range(0,matrix.shape[0]):
            for j in range(0,matrix.shape[1]):
                
                if matrix[i][j] == target[i][j]:
                    result[i][j] = 0
                    
                elif ((matrix[i][j] == UP and target[i][j] == DOWN)\
                    or (matrix[i][j] == DOWN and target[i][j] == UP) \
                    or (matrix[i][j] == LEFT and target[i][j] == RIGHT) \
                    or (matrix[i][j] == RIGHT and target[i][j] == LEFT)):
                    result[i][j] = 2
                    
                elif (matrix[i][j] != target[i][j]):
                    result[i][j] = 1
                    
    return result

In [110]:
print(circuits_check(matrix,target))

[[2 1 1]
 [2 2 1]
 [1 2 0]]
